# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

 tag-valid:
    name: Check for valid tag

    # Run only if it's a tag in general (as regex is not possible here)
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    # Save status for use in other jobs
    outputs:
      status: ${{ steps.check-tag.outputs.match }}

    steps:
      # Check for a valid tag
      - name: Check if trigger is a valid tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=match::true
          fi
          
 ter-release:
    name: TYPO3 TER release

    # Depend on a valid tag
    #needs: tag-valid
    #if: needs.tag-valid.outputs.status == 'true'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [8.1]

    env:
      # Add your extension key
      TYPO3_EXTENSION_KEY: google_cloud_storage_fal
      TYPO3_USER: ${{ secrets.TYPO3_USER }}
      TYPO3_PASSWORD: ${{ secrets.TYPO3_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.TYPO3_EXTENSION_KEY }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring, xml, soap, zip, curl

      - name: Install TYPO3 TER client
        run: composer global require namelesscoder/typo3-repository-client "^2.0" --prefer-dist --no-progress --no-suggest

      - name: Remove .git folder
        run: rm -rf ./$TYPO3_EXTENSION_KEY/.git

      - name: Remove .github folder
        run: rm -rf ./$TYPO3_EXTENSION_KEY/.github

      - name: Upload EXT:${{ env.TYPO3_EXTENSION_KEY }} as ${{ github.event.ref }} to TER
        run: php ~/.composer/vendor/bin/upload "./$TYPO3_EXTENSION_KEY" "$TYPO3_USER" "$TYPO3_PASSWORD" "${{ github.event.head_commit.message }}"
